const ErrorHander = require("../utils/errorHander");
const catchAsyncError = require("./catchAsyncError");
const jwt = require("jsonwebtoken");
const User = require("../models/userModels");

//Check the user login or not using cookies token generated by JWT web token
exports.isAuthenticate = catchAsyncError(async (req, res, next) => {
  const { token } = req.cookies;

  if (!token) {
    return next(
      new ErrorHander("Please Login First to access the Resources", 401)
    );
  }
  const decodeData = jwt.verify(token, process.env.JWT_SECRET);

  req.user = await User.findById(decodeData.id);
  next();
});

//Create ,Update product only done by admin
exports.authoriseRole = (...roles) => {
  return (req, res, next) => {
    if (!roles.includes("admin")) {
      return next(
        new ErrorHander(
          `Role : ${req.user.role} is not allowed to access the resources`,
          403
        )
      );
    }
    next();
  };
};
